apiVersion: apps/v1
kind: Deployment
metadata:
  name: comunidad-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comunidad-bot
  template:
    metadata:
      labels:
        app: comunidad-bot
    spec:
      containers:
        - name: api
          image: comunidad-bot:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: comunidad-bot-config
            - secretRef:
                name: comunidad-bot-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
