name: comunidad-bot-ci

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'config/**'
      - 'pyproject.toml'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'config/**'
      - 'pyproject.toml'
      - 'requirements.txt'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit & integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry (optional)
        if: env.DOCKER_USERNAME != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY || 'ghcr.io' }}
          username: ${{ env.DOCKER_USERNAME || github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile
          push: ${{ env.PUSH_IMAGE == 'true' }}
          # ghcr requires lowercase - force manual lowercase
          tags: ${{ env.DOCKER_REGISTRY || 'ghcr.io' }}/juancrzp/chatguard:comunidad-latest
        env:
          PUSH_IMAGE: ${{ vars.PUSH_IMAGE || 'false' }}
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
